#include <sqctypetable.h>

const ctypeEntry asciiTableCtypes[128] =
{
    {ctypeIsNone}, // NUL
    {ctypeIsNone}, // SOH
    {ctypeIsNone}, // STX
    {ctypeIsNone}, // ETX
    {ctypeIsNone}, // EOT
    {ctypeIsNone}, // ENQ
    {ctypeIsNone}, // ACK
    {ctypeIsNone}, // BEL
    {ctypeIsNone}, // BS
    {ctypeIsSpace}, // TAB
    {ctypeIsSpace}, // LF
    {ctypeIsSpace}, // VT
    {ctypeIsSpace}, // FF
    {ctypeIsSpace}, // CR
    {ctypeIsNone}, // SO
    {ctypeIsNone}, // SI
    {ctypeIsNone}, // DLE
    {ctypeIsNone}, // DC1
    {ctypeIsNone}, // DC2
    {ctypeIsNone}, // DC3
    {ctypeIsNone}, // DC4
    {ctypeIsNone}, // NAK
    {ctypeIsNone}, // SYN
    {ctypeIsNone}, // ETB
    {ctypeIsNone}, // CAN
    {ctypeIsNone}, // EM
    {ctypeIsNone}, // SUB
    {ctypeIsNone}, // ESC
    {ctypeIsNone}, // FS
    {ctypeIsNone}, // GS
    {ctypeIsNone}, // RS
    {ctypeIsNone}, // US
    {ctypeIsSpace}, // Space
    {ctypeIsNone}, // !
    {ctypeIsNone}, // "
    {ctypeIsNone}, // #
    {ctypeIsNone}, // $
    {ctypeIsNone}, // %
    {ctypeIsNone}, // &
    {ctypeIsNone}, // '
    {ctypeIsNone}, // (
    {ctypeIsNone}, // )
    {ctypeIsNone}, // *
    {ctypeIsNone}, // +
    {ctypeIsNone}, // ,
    {ctypeIsNone}, // -
    {ctypeIsNone}, // .
    {ctypeIsNone}, // /
    {ctypeIsNone}, // 0
    {ctypeIsNone}, // 1
    {ctypeIsNone}, // 2
    {ctypeIsNone}, // 3
    {ctypeIsNone}, // 4
    {ctypeIsNone}, // 5
    {ctypeIsNone}, // 6
    {ctypeIsNone}, // 7
    {ctypeIsNone}, // 8
    {ctypeIsNone}, // 9
    {ctypeIsNone}, // :
    {ctypeIsNone}, // ;
    {ctypeIsNone}, // <
    {ctypeIsNone}, // =
    {ctypeIsNone}, // >
    {ctypeIsNone}, // ?
    {ctypeIsNone}, // @
    {ctypeIsUpper}, // A
    {ctypeIsUpper}, // B
    {ctypeIsUpper}, // C
    {ctypeIsUpper}, // D
    {ctypeIsUpper}, // E
    {ctypeIsUpper}, // F
    {ctypeIsUpper}, // G
    {ctypeIsUpper}, // H
    {ctypeIsUpper}, // I
    {ctypeIsUpper}, // J
    {ctypeIsUpper}, // K
    {ctypeIsUpper}, // L
    {ctypeIsUpper}, // M
    {ctypeIsUpper}, // N
    {ctypeIsUpper}, // O
    {ctypeIsUpper}, // P
    {ctypeIsUpper}, // Q
    {ctypeIsUpper}, // R
    {ctypeIsUpper}, // S
    {ctypeIsUpper}, // T
    {ctypeIsUpper}, // U
    {ctypeIsUpper}, // V
    {ctypeIsUpper}, // W
    {ctypeIsUpper}, // X
    {ctypeIsUpper}, // Y
    {ctypeIsUpper}, // Z
    {ctypeIsNone}, // [
    {ctypeIsNone}, /* \ */
    {ctypeIsNone}, // ]
    {ctypeIsNone}, // ^
    {ctypeIsNone}, // _
    {ctypeIsNone}, // `
    {ctypeIsLower}, // a
    {ctypeIsLower}, // b
    {ctypeIsLower}, // c
    {ctypeIsLower}, // d
    {ctypeIsLower}, // e
    {ctypeIsLower}, // f
    {ctypeIsLower}, // g
    {ctypeIsLower}, // h
    {ctypeIsLower}, // i
    {ctypeIsLower}, // j
    {ctypeIsLower}, // k
    {ctypeIsLower}, // l
    {ctypeIsLower}, // m
    {ctypeIsLower}, // n
    {ctypeIsLower}, // o
    {ctypeIsLower}, // p
    {ctypeIsLower}, // q
    {ctypeIsLower}, // r
    {ctypeIsLower}, // s
    {ctypeIsLower}, // t
    {ctypeIsLower}, // u
    {ctypeIsLower}, // v
    {ctypeIsLower}, // w
    {ctypeIsLower}, // x
    {ctypeIsLower}, // y
    {ctypeIsLower}, // z
    {ctypeIsNone}, // {
    {ctypeIsNone}, // |
    {ctypeIsNone}, // }
    {ctypeIsNone}, // ~
    {ctypeIsNone}, // DEL
} ;